### PR TITLE
Some small fixes

### PR DESCRIPTION
**Pull request by davidx**
- fixes updated markdown requirement
- fixes no output gist save error.
- fixes delete of retry comment trigger.
- updates bashrc

### CODE REVIEW

**Comment by hazen** [comment]
Happy to +1 a YOLO. Just don't blame me when it breaks 😉

**Comment by paegun** [comment]
+1

||| markdown fix incoming in #42 needed, but otherwise improvements

**Comment by hazen** [comment]
:+1:

**Comment by davidx** [comment]
@javajolt @paegun Thanks!

**Pull request merged**
