### PR TITLE
typo in the instructions

### PR DESCRIPTION
**Pull request by ghost**
Guess I'm the first person to ever attempt to deploy this outside basho - it's 'bundler' not 'bundle'

### CODE REVIEW

**Comment by davidx** [comment]
Hey @bryanhuntesl! Sorry! Just noticed this. 
Thank you for your interest in the project and please let me know if you have any questions.
Regarding the bundler vs bundle, did you get an error? it may be a linux distro thing, like if using bundler from the apt-get package rather than gem ? 
I thought maybe the syntax had changed however this doc seems to indicate bundle exec <app> would still apply. All though I tried bundler exec as well and it also worked. 😄 
http://bundler.io/man/bundle-exec.1.html
Thanks!

**Comment by ghost** [comment]
This stuff changes so much in different environments. I think, and it was on a former computer, that I used ruby installed via brew, then gem install, then the command.

Dreadful bug reporting, I'll do better next time. Sorry!

**Comment by ghost** [comment]
Oh, on osx and docker maybe.

**Comment by ghost** [comment]
You still working with ruby? If you were to reimplement this with a view to a  containers for testing and runtime deployment - would you ever consider Elixir? I used Ruby for quite a long time before, perhaps 5 years on and off, but it sometimes seemed a bit like Perl on the packaging/stability side.

**Pull request closed without merging**
