### PR TITLE
Add ability to run commands in docker container

### PR DESCRIPTION
**Pull request by davidx**
This enables use of docker containers.

Currently one has to ensure a range of build dependencies are present in a shared environment for all builds. 😬 
This PR allows for a custom and portable build environment to work in. 
Features:
-  enable use of a docker image for all build steps. ( docker: true ) 
Mounts build directory as a volume.
Defaults to ubuntu:latest. 

Also works without docker:
- can inject environment variables ( env: )
- can set execution shell ( shell: /bin/bash )

config options:
```yaml
# required
docker: true
# optional
docker_image: ubuntu
shell: "/bin/bash"
env:
  BUNDLE_GEMFILE: Gemfile
  APP_VERSION: 26
```

Example pull request using docker with gcc:latest and demo of environment variables set from config.

https://github.com/davidx/prtester/pull/318

### CODE REVIEW

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by paegun** [comment]
- .gitignore should have an entry to exclude `vendor/`, bundle so the Gemfile manages this.
- ENV delete of (TOKEN|CLIENT_SECRET|PASS) may be a good thing to make note of to users of Thumbs, perhaps in the README, perhaps in a wiki article.
- run_command is a nice abstraction, running in shell or in docker, very nice.

**Comment by davidx** [comment]
@paegun I was having seriously issues trying to load the docker-api using the gemfile, thats why I vendor'ed it. I'll poke at it some more today.  Yep, also need to update the doc with the latest info. thanks!

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
- removed vendor dirs
- updated run commands

**Comment by paegun** [comment]
+1

**Pull request merged**
